name: Shellcheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        shopt -s nullglob
        shellcheck */*/build */*/post-install
